# Generated by Django 4.2.1 on 2023-05-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.BinaryField(null=True, verbose_name='Фото'),
        ),
    ]
