# Generated by Django 4.2.1 on 2023-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default=None, null=True, verbose_name='ссылка'),
        ),
    ]
