# Generated by Django 4.2.1 on 2023-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_project_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.FileField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
